--
-- INSTITUTIE (dev)
--
INSERT INTO NOM_STARE_INCARCARE(ID_NOM_STARE_INCARCARE,COD,DENUMIRE) VALUES(1, 'N', 'Noua');
INSERT INTO NOM_STARE_INCARCARE(ID_NOM_STARE_INCARCARE,COD,DENUMIRE) VALUES(2, 'A', 'In asteptare');
