--
-- INSTITUTIE (dev)
--
INSERT INTO NOM_INSTITUTIE(ID_NOM_INSTITUTIE,COD,DENUMIRE) VALUES(1, 'ANCPI', 'ANCPI');
INSERT INTO NOM_INSTITUTIE(ID_NOM_INSTITUTIE,COD,DENUMIRE) VALUES(2, 'ANAF', 'ANAF');
