INSERT INTO NOM_STARE_REGISTRU(ID_NOM_STARE_REGISTRU,COD,DENUMIRE) VALUES(SEQ_NOM_STARE_REGISTRU.NEXTVAL, 'S1', 'Stare 1');
INSERT INTO NOM_STARE_REGISTRU(ID_NOM_STARE_REGISTRU,COD,DENUMIRE) VALUES(SEQ_NOM_STARE_REGISTRU.NEXTVAL, 'S2', 'Stare 2');
INSERT INTO NOM_STARE_REGISTRU(ID_NOM_STARE_REGISTRU,COD,DENUMIRE) VALUES(SEQ_NOM_STARE_REGISTRU.NEXTVAL, 'S3', 'Stare 3');

