
INSERT INTO NOM_SURSA_REGISTRU(ID_NOM_SURSA_REGISTRU,COD,DENUMIRE) VALUES(SEQ_NOM_SURSA_REGISTRU.NEXTVAL, 'UPLOAD', 'Upload manual');
INSERT INTO NOM_SURSA_REGISTRU(ID_NOM_SURSA_REGISTRU,COD,DENUMIRE) VALUES(SEQ_NOM_SURSA_REGISTRU.NEXTVAL, 'UAT', 'Sistem software Uat');
INSERT INTO NOM_SURSA_REGISTRU(ID_NOM_SURSA_REGISTRU,COD,DENUMIRE) VALUES(SEQ_NOM_SURSA_REGISTRU.NEXTVAL, 'AID', 'Aplicatie introducere date');
