--
-- Nomenclatorul de judete (dev)
--
INSERT INTO NOM_JUDET(ID_NOM_JUDET, COD_ALFA, COD_SIRUTA, DENUMIRE, DATA_START, BASE_ID) VALUES (1, 'BC', '222', 'BACAU', SYSDATE, 0);
INSERT INTO NOM_JUDET(ID_NOM_JUDET, COD_ALFA, COD_SIRUTA, DENUMIRE, DATA_START, BASE_ID) VALUES (2, 'IS', '111', 'IASI', SYSDATE, 0);
INSERT INTO NOM_JUDET(ID_NOM_JUDET, COD_ALFA, COD_SIRUTA, DENUMIRE, DATA_START, BASE_ID) VALUES (3, 'SV', '333', 'SUCEAVA', SYSDATE, 0);
