--
-- UAT (dev)
--
INSERT INTO NOM_UAT(ID_NOM_UAT, COD_SIRUTA, DENUMIRE, FK_NOM_JUDET, DATA_START, BASE_ID) VALUES(1, '111', 'UAT 1', (SELECT ID_NOM_JUDET FROM NOM_JUDET WHERE DENUMIRE = 'IASI'), SYSDATE, 0);
INSERT INTO NOM_UAT(ID_NOM_UAT, COD_SIRUTA, DENUMIRE, FK_NOM_JUDET, DATA_START, BASE_ID) VALUES(2, '222', 'UAT 2', (SELECT ID_NOM_JUDET FROM NOM_JUDET WHERE DENUMIRE = 'IASI'), SYSDATE, 0);
INSERT INTO NOM_UAT(ID_NOM_UAT, COD_SIRUTA, DENUMIRE, FK_NOM_JUDET, DATA_START, BASE_ID) VALUES(3, '333', 'UAT 3', (SELECT ID_NOM_JUDET FROM NOM_JUDET WHERE DENUMIRE = 'IASI'), SYSDATE, 0);
