---CREATE TRIGGER IF NOT EXISTS GOSPODARIE_INS BEFORE INSERT ON GOSPODARIE FOR EACH ROW CALL "ro.uti.ran.core.utils.h2.lastModifiedTrigger";
--DROP TRIGGER IF EXISTS ADR_GOSP_INS;
--CREATE TRIGGER IF NOT EXISTS ADR_GOSP_INS BEFORE INSERT ON ADRESA_GOSPODARIE FOR EACH ROW CALL "ro.uti.ran.core.database.triggers.AdresaGospodarieTrigger";

--DROP TRIGGER IF EXISTS D_PF_INS;
--CREATE TRIGGER IF NOT EXISTS DE_PF_INS BEFORE INSERT ON DETINATOR_PF FOR EACH ROW CALL "ro.uti.ran.core.database.triggers.DetinatorPfTrigger";


--DROP TRIGGER IF EXISTS ADR_INS;
--CREATE TRIGGER IF NOT EXISTS ADR_INS BEFORE INSERT ON ADRESA FOR EACH ROW CALL "ro.uti.ran.core.database.triggers.AdresaTrigger";

DROP TRIGGER IF EXISTS REG_COMMIT;
CREATE TRIGGER IF NOT EXISTS REG_COMMIT AFTER INSERT ON REGISTRU FOR EACH ROW CALL "ro.uti.ran.core.database.triggers.RegistruCommitTrigger";



